config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]
  resources :attendanceships, only: [:create]
  resources :invitations, only: [:create]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendanceship.rb
class Attendanceship < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'event_id'
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'

  validates_uniqueness_of :user_id, scope: :event_id
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :attendanceships#, foreign_key: 'event_id'
  has_many :attendees, through: :attendanceships, source: :attendee
  has_many :invitations
  has_many :invitees, through: :invitations

  scope :previous, -> { where("time <= :now_time", {now_time: Time.now}) }
  scope :upcoming, -> { where("time > :now_time", {now_time: Time.now}) }
  # Replaced with scope
    #def self.previous
    #  Event.all.where("time <= :now_time", {now_time: Time.now})
    #end

    #def self.upcoming
    #  Event.all.where("time > :now_time", {now_time: Time.now})
    #end

  

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  attr_accessor :user_name
  belongs_to :invited_event, class_name: 'Event', foreign_key: 'event_id'
  belongs_to :invitee, class_name: 'User', foreign_key: 'user_id'

  validates_uniqueness_of :user_id, scope: :event_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'

  has_many :attendanceships#, foreign_key: 'user_id'
  has_many :attended_events, through: :attendanceships, source: :attended_event
  has_many :invitations
  has_many :invited_events, through: :invitations, source: :invited_event

  validates :email, presence: true,
                    uniqueness: true


  def upcoming_events
    self.attended_events.where("time > :now_time", {now_time: Time.now}) 
  end

  def previous_events
    self.attended_events.where("time <= :now_time", {now_time: Time.now})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/attendanceships_controller.rb
class AttendanceshipsController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    attendance = event.attendanceships.build(user_id: current_user.id)
    if attendance.save
      flash[:success] = "You've sucessfully RSVPed to #{event.name}"
      redirect_to event
    else
      flash[:danger] = "You were not be added to the attandance list: #{attendance.errors.full_messages}"
      redirect_to event
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to user_path(current_user[:id])
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendanceship = Attendanceship.new
    @invitation = Invitation.new
  end

  private
    def event_params
      params.require(:event).permit(:name, :description, :time, :location)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    user = User.find_by(name: params[:invitation][:user_name])
    invite = event.invitations.build(user_id: user.id)
    if invite.save
      flash[:success] = "Successfully invited #{user.name}"
      redirect_to event
    else
      flash[:danger] = "Could not invite #{user.name}: #{invite.errors.full_messages}"
      redirect_to event
    end
                        
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in(user)
      flash[:success] = "Welcome #{user.name}"
      redirect_to user_path(user)
    else
      flash[:danger] = 'Invalid email'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome"
      redirect_to user_path(@user)
    else
      flash[:danger] = "Error creating account: #{@user.errors.messages}"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @previous_events = @user.previous_events
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendanceships_helper.rb
module AttendanceshipsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>All Events</h1>
<h3>Upcoming Events</h3>
<ol>
  <% Event.upcoming.each do |event| %>
    <li>
      <%= link_to "#{event.name}", event %>
    </li>
  <% end %>
</ol>

<h3>Previous Events</h3>
<ol>
  <% Event.previous.each do |event| %>
    <li><%= link_to "#{event.name}", event %></li>
  <% end %>
</ol>

app/views/events/new.html.erb
<h1>Create a new Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @event do |f| %>
      <%= f.label :event_name %>
      <%= f.text_field :name%>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :location %>
      <%= f.text_field :location %>

      <%= f.label :date_and_time %>
      <%= f.text_field :time %>

      <%= f.submit 'Create Event', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
  <% if current_user == @event.creator %>
    <%= form_for @invitation, url: invitations_path do |f| %>
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>

      <%= hidden_field_tag "event_id", "#{@event.id}" %>
      <%= f.submit 'Invite this user', class: "btn btn-primary" %>
    <% end %>
  <% end %>
</p>

<h3>Event description</h3> 
<p><%= @event.description %></p>

<h3>Event Location</h3>
<p><%= @event.location %></p>

<h3>Event Date/Time</h3>
<p><%= @event.time %></p>

<p>
  This Event was created <%= time_ago_in_words(@event.created_at) %> ago by <%= @event.creator.name %>
</p>

<p>
  <%= form_for @attendanceship, url: attendanceships_path  do |f| %>
    <%= hidden_field_tag "event_id", "#{@event.id}" %>
    <%= f.submit 'Attend This Event', class: "btn btn-primary" %>
  <% end %>
</p>


    

<p>
Attendees: 
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= link_to "#{attendee.name}", user_path(attendee) %></li>
  <% end %>
</ul>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/lbrian357/private-events">Private Events source code</a> by <a href="https://github.com/lbrian357">Brian Li</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://weblog.rubyonrails.org/news/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Private Events', root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'All Events', events_path %></li>
          <li><%= link_to 'My Events', user_path(@current_user) %></li>
          <li><%= link_to 'New Event', new_event_path %></li>
          <li><%= link_to 'Logout', logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to 'Sign up', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <br>
      <%= content_tag(:p, content_tag(:em, "INFO: #{message}")) %>
    <% end %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Private Events</h1>
  <h2>
    Create Events and invite other members or RSVP to other members' events
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.submit 'Create account', class: "btn btn-primary" %>
    <% end %> 
  </div>
</div>

app/views/users/show.html.erb
<h1><%=@user.name%></h1>

<% if @user.invited_events.any? %>
  <h3>Invites</h3>
  <ul>
    <% @user.invited_events.each do |event| %>
      <li><%= link_to "#{event.name}", event %></li>
    <% end %>
  </ul>
<% end %>

<% if @user.created_events.any? %>
  <h3>Events created by <%= @user.name %> (<%= @user.created_events.count %>)</h3>
  <ol>
    <% @user.created_events.each do |event| %>
      <li>
        <%=link_to "#{event.name}", event %>
      </li>

    <% end %>
  </ol>
<% else %>
  <h3><%= @user.name %> hasn't created an Event yet!</h3>
<% end %>

<% if @upcoming_events.any? %>
  <h3><%= @user.name %> is going to attend:</h3>
  <ul> 
    <% @upcoming_events.each do |event| %>
      <li><%= link_to "#{event.name}", event %></li>
    <% end %>
  </ul>
<% else %>
  <h3><%= @user.name %> isn't going to any Events</h3>
<% end %>

<% if @previous_events.any? %>
  <h3><%= @user.name %> has attended:</h3>
  <ul>
    <% @previous_events.each do |event| %>
      <li><%= link_to "#{event.name}", event %></li>
    <% end %>
  </ul>
<% else %>
  <h3><%= @user.name %> hasn't previously attended any Events yet.</h3>
<% end %>